### ISSUE TITLE
Use with elements without a background

### ISSUE THREAD

**Issue by pixedelic** [nk-o/jarallax#1]
Hello, great script, thank you for sharing. Any plan to extend it to use it for elements without a background image, just to move them when you scroll or to detect when they are in viewport (I know it is out of scope, but it seems it has great potentialities).

TIA, Manuel :-)

**Comment by nk-o** [comment]
Hi, Manuel.

Thank you for using jarallax. I wanted to add background parallax video and may be opacity animation for inner text. But It will not implemented soon, because I satisfied the current functionality.

Best regards, nK.

**Comment by pixedelic** [comment]
Thank you for the quick reply!
