### ISSUE TITLE
How do I destroy an instance of Jarallax?

### ISSUE THREAD

**Issue by vinnlee** [nk-o/jarallax#102]
### Issue description:
I want to stop the parallax effect on a specific window size when resize the browser window but it's seem there is no option to control that. 🤔

### Version used: 
Jarallax v1.10.3
Elements Extension for Jarallax v1.0.0

**Comment by nk-o** [comment]
@vinnlee you can watch for window resize event and [`destroy`](https://github.com/nk-o/jarallax#methods) the plugin when needed.

I see there is a bug with destroying blocks that use Elements extension, will be fixed in the future updates (you also can fix it by yourself and make a Pull Request).
