### ISSUE TITLE
Add an optional "muted" property for videos

### ISSUE THREAD

**Issue by alxriche** [nk-o/jarallax#107]
### Issue description:
This will avoid Android stopping other audio sources when displaying a Jarallax video.
Furthermore, this will also avoid Chrome 66 and later versions blocking autoplay on Jarallax videos.

### Version used:
1.9

**Comment by nk-o** [comment]
@alxriche there is **videoVolume** option, that set to 0 by default. And browsers work with this option fine. Maybe I don't understand something, could you give me more information or example on codepen, where I can see the issue.
