### ISSUE TITLE
Provide release without demo content

### ISSUE THREAD

**Issue by kybersoft** [nk-o/jarallax#108]
### Issue description:

Hi and thank you for great library. Current zip/tar archive has more than 50 MB because of 2 videos and few images inside. Is there any chance to provide zip without demo folder? It would really help when someone is using composer for adding into project and this is ruining his connection :-)

**Comment by nk-o** [comment]
You can use NPM to install dependencies. Demo directory will not be downloaded.

**Comment by kybersoft** [comment]
Thank you @nk-o , I tested it using NPM and it works nicely.
