### ISSUE TITLE
EdgeHTML 17 and visual issues with demonstration-page

### ISSUE THREAD

**Issue by pxamike** [nk-o/jarallax#110]
I noticed that jarallax seems to work worse in the latest Microsoft Edge (EdgeHTML 17) that came with Windows 10 April 2018 update, compared to EdgeHTML 16.

I tried the demonstration page on latest commit (e197548c) locally, but it seems to happen on the demo-site also: https://free.nkdev.info/jarallax/ (which uses 1.10.2). Tests were done in BrowserStack. Perhaps this is more an issue with the demonstration page than the jarallax-library itself?

In EdgeHTML17 all the full-width jarallax images are aligned to the top of the screen. So all the full-width jarallax image-areas further down the page are blank white areas. In 16 it looks the same as current Chrome or Firefox. 

EdgeHTML16:
![bs_win10_edge_16 0](https://user-images.githubusercontent.com/12510409/41342067-9aea466c-6efb-11e8-930f-34a4c4e8b047.jpg)

EdgeHTML17:
![bs_win10_edge_17 0](https://user-images.githubusercontent.com/12510409/41342077-a0b535d4-6efb-11e8-8009-1a8216f99b07.jpg)

I was able to "fix" the behaviour by disabling the "z-index: -100;" on the inline css on the jarallax-container, but I'm sure this is not a good solution and it would have other side-effects (f.ex. if there were content inside the jarallax, it would probably overlap it).

Unmodified:
![bs_win10_edge_17 0 unmodified](https://user-images.githubusercontent.com/12510409/41342110-b7fdf046-6efb-11e8-9054-29a4b9766ef8.jpg)

Modified:
![bs_win10_edge_17 0 modified](https://user-images.githubusercontent.com/12510409/41342111-b81b91a0-6efb-11e8-8ed5-56fe5106fe73.jpg)

**Comment by vhusaruk92** [comment]
Agree. I rewrote 'z-index' to z-index: 0 or  $(this).css('z-index', 'unset') in my projects to make parallax works fine

**Comment by lmuzquiz** [comment]
Had the same issue and discovered that after doing:

  <style>
    #jarallax-container-0 {
      z-index: 0 !important;
    }
  </style>

 I was calling the image using the **_style_** attribute combined with the **_background-image_** e.g: 

```
<div class="jarallax big-screen-max-height">
  <img class="jarallax-img" style="background-image: url('assets/img/image.jpg');">
</div>
```
And it was being displayed on Microsoft Edge after the z-index hack,  but still a bit weird. So i changed my code to call the image with the src attribute like this:

```
<div class="jarallax big-screen-max-height">
  <img class="jarallax-img" src="assets/img/image.jpg" alt="">
</div>
```
