### ISSUE TITLE
Request to make it work if image is inside iframe

### ISSUE THREAD

**Issue by Sahero** [nk-o/jarallax#111]
It doesn't work if it is inside an iframe. Is it possible to implement this feature?

**Comment by nk-o** [comment]
Please, provide an online example, it is working for me in iframes.

**Comment by Sahero** [comment]
Hi @nk-o ,

Here is the demo link in codepen: 
https://codepen.io/Sahero/pen/ERJvJp.

I want to listen to the top parent scroll event for parallax view.

Thank youz

**Comment by nk-o** [comment]
This is too specific, I don't think it will be implemented.

**Comment by nk-o** [comment]
@tdanielcox as I said, it is too specific for background parallax.

You can create another repo and make an extension for Jarallax, but this code will not be included in the main repo.
