### ISSUE TITLE
Transform Translate Header Image

### ISSUE THREAD

**Issue by horitani** [nk-o/jarallax#113]
### Issue description:

hello!

i am using jarallax on several **elements** on a single page. everything works fine - but the first image, which is the header image, is always translated3d(0, **somepixels**, 0) on load. is there a way to fix this ?

Screenshot:
![bildschirmfoto 2018-07-04 um 15 48 56](https://user-images.githubusercontent.com/31068005/42280713-d068ff8e-7fa1-11e8-9cb2-9b8c8b3770a4.png)

thank you all in advance!

### Code to reproduce the issue (HTML blocks + JavaScript initialization)
```javascript
$('.jarallax').jarallax({
    type: 'element',
    speed: '100 0',

    onInit: function() {

    }

});
```

```html
<div class="page-image jarallax" style="transform: translate3d(0px, 26.2788px, 0px); z-index: 0;" data-jarallax-original-styles="transform: translate3d(0px, 26.2788px, 0px);">
    <img src="/userfiles/images/content/myimage.jpg" alt="Header-Image" width="1680" height="735">
    <div style="position: absolute; top: 0px; left: 0px; width: 100%; height: 100%; overflow: hidden; pointer-events: none; z-index: -100;" id="jarallax-container-0"><div style="position: absolute;"></div></div>
</div>
```

### Version used:
Latest Version

**Comment by nk-o** [comment]
If someone wants to resolve this, make a PR, close for now.
