### ISSUE TITLE
Slow with SVG elements

### ISSUE THREAD

**Issue by UserGalileo** [nk-o/jarallax#115]
### Issue description:
I'm using this library with SVGs elements, I add the parallax on the g element (child of svg) and it works, but it's not smooth. If I scroll too fast I can see the svg moving after the scroll has finished.

Any workarounds or suggestions?
Thanks!

### Version used:
(Did you try using the develop branch from GitHub? There's a chance your issue has already been addressed there)
Last version.

### Code to reproduce the issue (HTML blocks + JavaScript initialization)
```html
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" x="0px" y="0px"
      height="100%" viewBox="0 0 1139.362 1380.406" xml:space="preserve">
        <g class="jarallax" data-jarallax-element="50"  opacity="0.75">
          <path fill="none" d="M1138.929,27.6c-73.348,126.491-132.202,261.227-184.366,372.676
      C845.725,632.762,752.699,735.252,550.855,887.87c-171.642,129.781-260.694,340.207-451.076,455.832
      c-22.892,13.902-46.671,26.088-71.19,36.242"/>
        </g>
      </svg>

```

```javascript
    jarallax(document.querySelectorAll('.jarallax'));
```

**Comment by nk-o** [comment]
I don't see any difference in performance.

Maybe the problem in the size of the block. Browser trying to render this large block and this requires more resources than for small blocks.
