### ISSUE TITLE
Disable Parallax on mobile is not working

### ISSUE THREAD

**Issue by nkanoi** [nk-o/jarallax#116]
### Issue description:
jarallax(document.querySelectorAll('.jarallax'), {
    	disableParallax: /iPad|iPhone|iPod|Android/,
	    disableVideo: /iPad|iPhone|iPod|Android/
	});

### Version used:
(Did you try using the develop branch from GitHub? There's a chance your issue has already been addressed there)

### Code to reproduce the issue (HTML blocks + JavaScript initialization)
```html

```

```javascript

```

**Comment by nk-o** [comment]
Working for me. Please, show me an online example with the bug.

**Comment by nk-o** [comment]
Сlosed because this is a duplicate of https://github.com/nk-o/jarallax/issues/97
