### ISSUE TITLE
Issue with require js

### ISSUE THREAD

**Issue by vesse13** [nk-o/jarallax#117]
### Issue description:
Hi, when i load Jarallax.js with require.js, i can't use data-attributes to init the parallax. Do you have an idea to solve this ? 

### Version used:
(Did you try using the develop branch from GitHub? There's a chance your issue has already been addressed there)
last

### Code to reproduce the issue (HTML blocks + JavaScript initialization)
```html

```

```javascript

```

**Comment by nk-o** [comment]
Hi.

Since you use require.js, you need to call Jarallax manually. Run this code after the page loaded:

```javascript
jarallax(document.querySelectorAll('[data-jarallax]'));
```
