### ISSUE TITLE
Jarallax Element - TypeError: Cannot read property 'y' of undefined

### ISSUE THREAD

**Issue by thetwosents** [nk-o/jarallax#119]
### Issue description:
data-jarallax-element="-50" not working on elements. Gives error "TypeError: Cannot read property 'y' of undefined" Trying to use on a basic H1 with position relative. Cannot get to work on any elements without throwing this error :/

### Version used:
(Did you try using the develop branch from GitHub? There's a chance your issue has already been addressed there)
1.10.4

### Code to reproduce the issue (HTML blocks + JavaScript initialization)
```html
<h1 data-jarallax-element="-50">Hey</h1>
```

```javascript

```

Thanks in advance!

**Comment by nk-o** [comment]
It is working fine for me without any errors. Have you included elements extension script? https://github.com/nk-o/jarallax#browser
