### ISSUE TITLE
Wrong documentation Options

### ISSUE THREAD

**Issue by obendev** [nk-o/jarallax#121]
### Issue description:
Hey!
I use the options `data-img-size="contain"` and `data-img-position="90% center"` but the documentation (README.md) says the options are: `imgSize` and `imgPosition`.

**Comment by nk-o** [comment]
These options (imgSize, imgPosition) used for JS initialization. For data attributes there is a small note here - https://github.com/nk-o/jarallax#a-data-attribute-way.

**Comment by obendev** [comment]
Ah okay.
Maybe make a seperate list for it?

**Comment by nk-o** [comment]
No, I think it is not so hard to convert camelCase to dash-case without an additional table.

**Comment by obendev** [comment]
Guess this can be closed then. :)
