### ISSUE TITLE
Incorrect .jarallax-img height calculation

### ISSUE THREAD

**Issue by MarcusCemes** [nk-o/jarallax#122]
Hi, let me start by saying that your library is amazing. I've tried various similar libraries, but this one trumps them all. Thank you for taking the time to develop and release something like this to the public!

### Issue description:
The height of .jarallax-img (inside of #jarallax-container-x) does not seem to be correctly calculated.
The problem is not present in a traditional implementation of Jarallax, however, when using portrait style parallax backgrounds, the height is miscalculated and the image is oversized/cropped beyond what could be possible.

### Version used:
Latest release: 1.10.4

### Code to reproduce the issue (HTML blocks + JavaScript initialization)
I have made a little codepen to demonstrate the problem:
[https://codepen.io/MarcusCemes/pen/XPyVPx](https://codepen.io/MarcusCemes/pen/XPyVPx
)
The first section shows a correctly sized background.
The second section shows a vertical implementation with a 100vw by 200vh size (viewport is a standard 16:9), and a jarallax speed 0 background. The height is overcalculated, and the image is cropped beyond what is reasonble due to object-fit: cover, having to cover a landscape image into a portrait container that is 50% larger than what it should be.
See the third section for a typical fixed-background to see the least possible crop for that image.
The fourth section shows the same sized jarallax use, but with speed 1... This time the height is correct.

The reason for the chosen speeds is that the height is correct for speed 1 (a.k.a. "no parallax"), the height is equal to the **container size**.
As the speed tends towards 0, the height is increased to beyond the container, when in fact at speed 0 it should theoretically be equal to the **viewport size**, therefore actually less than the container height.
Perhaps my math is wrong, I'm not sure how this would equate to inline images, but for full screen backgrounds it is the case.
I'm not sure how the size and positioning are calculated, it might be a more complicated problem than I realise. It might be an issue with the jarallax container being larger than the viewport, or for a container who's aspect ratio is too small (portrait).

### Closing Note
This issue was brought up in #45 I believe, I wanted to shed some more light upon it. With the web supposed to be an optimized environment, not having to rely on very high-resolution images (sometimes this isn't even possible) would be more ideal. I have seen 200vh parallax backgrounds before, and I have to say, they do look quite stunning. Although your library is amazing, this little kink has started pushing me to develop a custom solution once my production build is "complete", which although would definitely be less compatible and optimized, would fill in the gap and give me more creative freedom on modern browsers. Fixing this or providing a full-background work around (config option?) would make the library more universal and benefit more people!

If you think there's any way I can help, let me know. Thanks!

**Comment by nk-o** [comment]
Yeah, thank you. I have never used oversized blocks. In calculation need to be added comparison of screen height and block height. I will test it before the future updates.

**Comment by moltar** [comment]
I wonder if height change on a scroll on mobile is related to this issue.

This only happens on an actual mobile device, not in "Responsive Design Mode" (Safari). Tested on iPhone SE.

A visual screencast of the jumpy: https://youtu.be/QRuA8x0w8H8

Here is the inline CSS video: http://take.ms/pA7kp

The CSS shown is for the child `div` of `jarallax-container-0` element.

**Comment by nk-o** [comment]
@moltar this is not a bug and not related to the issue created by Marcus. When you scroll the page in mobile Chrome, window height is changed and fired `resize` event and parallax needs recalculation, so you see the jumping.

**Comment by moltar** [comment]
@nk-o But the demo I posted is in Safari, not Chrome. Is there any workarounds for this?

**Comment by nk-o** [comment]
@moltar both, Chrome and Safari resizing window after scroll. Look at the bottom of your screen, there is a toolbar, that show/hide when you scroll.

**Comment by moltar** [comment]
@nk-o Are there any reasonable fixes for this?

**Comment by moltar** [comment]
Seems like something like this might work, not using jQuery of course: https://stackoverflow.com/a/24212316

As we probably don't care about the height change anyways, right? Or do we? If we only care about the window width, then maybe we shouldn't trust the `resize` event.

**Comment by nk-o** [comment]
Window height is used for parallax calculation, so we need to recalculate parallax position after resize.

**Comment by moltar** [comment]
Maybe then ignore window height change, as there is no way to change the height on mobile as far as I know. At least not on iOS.

**Comment by nk-o** [comment]
@MarcusCemes could you test the latest version? Should be fixed now.

**Comment by MarcusCemes** [comment]
Fantastic, I did some testing on the latest version and I'm unable to break it. It works beautifully, the sizes are intelligently calculated to the container and the viewport, in regards to the chosen jarallax speed.

Thank you for taking the time to address this issue, it's a great library and I hope that others will be able to benefit from new possibilities.

@moltar This is a tricky one, and even large websites have problems with this. They just try and smoothen it out as to not make people notice the glitch. iOS and Android have a dynamic viewport size, this is very unfriendly to any viewport-based CSS or Javascript. CSS just tends to be less noticeable, because it can be optimized internally by the browser.
Javascript is not the most performant language, and mobile devices will only fire resize events when absolutely necessary, hence the sudden jump. Ignoring the height would make the jarallax calculations incorrect, and as soon as you start scrolling you would get disturbing missing spaces. It's a design kink with mobile browsers, I haven't heard of an effective solution, and more logic would slow down everything even more. Mobile users just have to deal with it... It's a miracle that parallax even works on mobile today

**Comment by moltar** [comment]
@MarcusCemes This is not true. Here is an example that works perfectly and smooth on mobile and does not resize: https://htmlstream.com/preview/space-v1.1/html/home/index.html

It uses a `dzsparallaxer` commercial plugin.

**Comment by nk-o** [comment]
@moltar this plugin uses different calculation method (not strict as Jarallax) + smooth position change, so the image position is changing with a small animation and not jumps. Jarallax has a small problem with performance on mobile devices, so I will try to fix this in the next update, the jumping should be not visible as hard as now.

Look at this page on your mobile device to see how the screen size changes: https://free.nkdev.info/jarallax/test-window-resize-swipe.html

p.s. I close this issue to prevent future offtopic.
