### ISSUE TITLE
Video is not responsive

### ISSUE THREAD

**Issue by barjinder2014** [nk-o/jarallax#125]
### Issue description:
I am using Jarallax js to add video on the header area of my site, but the video is not looking good in mobile devices, it's not responsive and taking the very big height. Is there any solution there which I can use to make it responsive?

### Version used: 1.10.5
(Did you try using the develop branch from GitHub? There's a chance your issue has already been addressed there)

### Code to reproduce the issue (HTML blocks + JavaScript initialization)
```html

```

```javascript

```

**Comment by nk-o** [comment]
Images and Videos cover the full size of the selected block. So, you can manually change the size of your parallax blocks to make it "responsive" as you need.

**Comment by BaadalAdam** [comment]
@nk-o Even while the parallax block's width and height is defined for mobile, the video is scaled up and is not responsive! How should I tackle this? 

I have used the latest version of pluguin
