### ISSUE TITLE
How to make video sound play automatically when page is loaded?

### ISSUE THREAD

**Issue by zhelly** [nk-o/jarallax#128]
### Issue description:
The video is muted.

### Version used:
 Video Background Extension for Jarallax
Version : 1.0.1

### Code to reproduce the issue (HTML blocks + JavaScript initialization)
```html

```

```javascript

```

**Comment by nk-o** [comment]
It is not possible to have video autoplay with sound. https://developers.google.com/web/updates/2017/09/autoplay-policy-changes

The only way - unmute it after some user action. Example: https://codepen.io/_nK/pen/GQyvdZ
