### ISSUE TITLE
testing scrolling on iphone, ipad and android

### ISSUE THREAD

**Issue by antoniomt** [nk-o/jarallax#130]
Hello, I'm bothered with scrolling on mobile devices. In android the scrolling is a bit shaky more without many problems, already on the iphone and ipad and much more noticeable and causes a discomfort when browsing the site. Would there be any solution for the scrolling to occur cleanly?

I'm using version 1.10.6

Thank you.

**Comment by misha2016** [comment]
I have the same issues. it's less noticeable when you set your speed close to 1, but still visible

**Comment by alexjohnwiseman** [comment]
Same issue here

**Comment by eboy79** [comment]
Looks like I have the same issues too, ios is very jittery with random scaling as you scroll too.
