### ISSUE TITLE
Load video when in view 

### ISSUE THREAD

**Issue by ibrahimhajjaj** [nk-o/jarallax#138]
### Issue description:

Is there is a function or a call back that I can use to start loading the video after the page load ?!

e.g I have 5 videos on a single page and I want them to load only after the page load.
haven't seen any callback on readme

**Comment by nk-o** [comment]
You can only init jarallax manually using js https://github.com/nk-o/jarallax#b-javascript-way.

**Comment by ibrahimhajjaj** [comment]
thanks for your fast reply, so if I use it like the bellow code, Jarallax will initiate jarallax-container-0 div after loading the page?

and what if I add the data-jarallax-video=""  attr after the page loading will it work?

 `
   $(window).on("load",function () {

           $('.jarallax').jarallax({
                 speed: 0.2
            });

        });
`

**Comment by nk-o** [comment]
Your code will work after page load. Video options for JS initialization you can see here - https://github.com/nk-o/jarallax#options-for-video--supported-all-default-options

**Comment by ibrahimhajjaj** [comment]
the problem was related to pagepiling, thanks for your help, n keep the goog work!
