### ISSUE TITLE
Youtube video on fallback image after page refresh

### ISSUE THREAD

**Issue by cedric-bogota** [nk-o/jarallax#140]
Hello,

When I load a youtube video, it works perfectly each time I open the page on a new chrome tab.

However when I refresh the tab, the youtube video is stuck on the fallback image. When I clear the cache on my browser and then reload the page, the video starts normally. I tried to insert the no-cache meta in the head content, but it did not fix that issue.

Any idea?

Thanks !

Cedric

**Comment by nk-o** [comment]
Hi Cedric.

An online example will be perfect to see the bug. Use https://codepen.io/ if possible.

**Comment by cedric-bogota** [comment]
Hu Nikita, thanks for your feedback.
The page is www.oribama.com (through shopify). The first background video (top) is a MP4 file and works fine, the video below is from youtube and get frozen as soon as I refresh the page. I am looking to provide an example through codepen.
Thanks,
Cedric
