### ISSUE TITLE
How can I change the "background-position" from the default 50% 50%  to my value?

### ISSUE THREAD

**Issue by fitoparedes** [nk-o/jarallax#141]
### Issue description: 
Thanks for the incredible plugin first!. I'm calling the plugin with the jQuery way and with the initialization CSS code. Then I'm trying to move the position of the background image, but I cant. How can I change the "background-position" from the default 50% 50%  to my value (without modyfing it from jarallax.js) ?

### Version used:Latest
(Did you try using the develop branch from GitHub? There's a chance your issue has already been addressed there)

### Code to reproduce the issue (HTML blocks + JavaScript initialization)
```html
<section class="jarallax" style="background-image: url(img/bg-img/32.jpg);">
     <!-- Content -->
</section>
```

```javascript
$('.jarallax').jarallax({
    speed: 0.2
});
```

**Comment by fitoparedes** [comment]
Thanks a lot max-ci
I'm very sorry for my inexperience, I forgot the quotes, '' 
I'm a newbie.

**Comment by MrSenhaji** [comment]
$('.jarallax').jarallax({
    speed: 0.2,
    **imgPosition**: '20% 60%'
});

**Comment by MrSenhaji** [comment]
> https://github.com/nk-o/jarallax#options
> 
> ```js
> $('.jarallax').jarallax({
>     speed: 0.2,
>     imgPoisition: '20% 60%'
> });
> ```

change imgPoisition to imgPosition

**Comment by hidegh** [comment]
Well, it changes the X position, but not the Y;

**Comment by hidegh** [comment]
with object fit: cover I can alter the X position, but the Y position remains unchanged.
