### ISSUE TITLE
Video volume via data attribute

### ISSUE THREAD

**Issue by avilesasturias** [nk-o/jarallax#142]
Hi,

Thanks so much for this amazing plugin, all is working fine and great.
I do have the following question, is it possible to set the video volume via data attribute? or is this only possible via javascript initialization?

I created the following fiddle: [https://jsfiddle.net/3470sLd9/](https://jsfiddle.net/3470sLd9/)
where I tried with videoVolume and also prepending data- to it, but I can't seem to get it working.

Thanks.

**Comment by nk-o** [comment]
Hi.

Unfortunately, unmuted video autoplay will not work since this one: https://developers.google.com/web/updates/2017/09/autoplay-policy-changes

Regards, nK.

**Comment by avilesasturias** [comment]
Thanks @nk-o 
Again, lovely plugin :)
