### ISSUE TITLE
Jarallax with lazy video

### ISSUE THREAD

**Issue by jpuri** [nk-o/jarallax#144]
### Issue description:
Hi @nk-o , thanks a lot for this awesome lib. It is working very well for background videos in my application.
I have a requirement to lazy load the videos, is that something this lib supports ?

Thanks in advance for help :)

### Version used:
(Did you try using the develop branch from GitHub? There's a chance your issue has already been addressed there)
1.0.0

### Code to reproduce the issue (HTML blocks + JavaScript initialization)
```html

```

```javascript

```

**Comment by nk-o** [comment]
Hey.

Lazy loading is not supported for videos. You can only make it by yourself with custom scripting.
