### ISSUE TITLE
How can I disable the parallax of an element on mobile?

### ISSUE THREAD

**Issue by andreafrison** [nk-o/jarallax#146]
...or how can I initialize the parallax of an element via jQuery? 
["type"](https://github.com/nk-o/jarallax#options-for-element-parallax) would not seem to work!

**Comment by nk-o** [comment]
How to disable on mobile devices - https://github.com/nk-o/jarallax#disable-on-mobile-devices

How to initialize using jQuery - https://github.com/nk-o/jarallax#c-jquery-way
