### ISSUE TITLE
Pause/unpause and mute/unmute

### ISSUE THREAD

**Issue by makshh** [nk-o/jarallax#15]
It's not an issue, rather a question:

Is it possible to pause/unpause or mute/unmute videos?

I would like to have two buttons on my parallax container to toggle play and sound.

**Comment by nk-o** [comment]
Play/pause possible, but video will autoplay after window resize/scroll.

```javascript
var item = $('.jarallax')[0];

// pause
item.jarallax.video.pause();

// play
item.jarallax.video.play();
```

You can customize code, but for now it's not work and will not work.

**Comment by maxiris** [comment]
Hello,

This solution doesn't seem to be working on the current release of Jarallax,  is there another way to do this? 

Thank you for your amazing plugin! :)

Max
