### ISSUE TITLE
Is it possible to play videos with HEVC codec?

### ISSUE THREAD

**Issue by sandman18** [nk-o/jarallax#156]
### Issue description:
Can you play videos with the hevc codec with Jarrallax?

### Version used:
(Did you try using the develop branch from GitHub? There's a chance your issue has already been addressed there)

### Code to reproduce the issue (HTML blocks + JavaScript initialization)
```html

```

```javascript

```

**Comment by nk-o** [comment]
I don't think it is possible with the current code. Video string parser accepts URL and video extension (format) only

https://github.com/nk-o/video-worker/blob/a28955da13c670602e6f640b176e55ab924f9e34/src/video-worker.esm.js#L99-L115
