### ISSUE TITLE
npm install @types/jarallax

### ISSUE THREAD

**Issue by CaveDweller92** [nk-o/jarallax#160]
### Issue description:
Cannot import jarallax to my vue project.  I'm getting the following error. 

**Try `npm install @types/jarallax` if it exists or add a new declaration (.d.ts) file containing `declare module 'jarallax';`**

I tried to do the steps mentioned in the following url but couldn't find the index.d.ts in node_modules.

[Add TypeScript support
](https://github.com/nk-o/jarallax/pull/91#issuecomment-408668356)

### Version used:
1.12.0

### Code to reproduce the issue (HTML blocks +TypeScript initialization)
```html
    <div class="jarallax">
      <img class="jarallax-img" ssrc="..\assets\images\slider\IMG_7509-2.jpg" alt />
      Your content here...
    </div>
```

```Typescript
import { jarallax, jarallaxElement, jarallaxVideo } from "jarallax";
   jarallax(document.querySelectorAll(".jarallax"), {
      speed: 0.2
    });
```

**Comment by integrate-your-mind** [comment]
I'm going to attempt to take a look into this when I have some time as I really like jarallax and it doesn't seem like it will be too painful to convert to ts. Just forked will post updates as they happen.

> ### Issue description:
> Cannot import jarallax to my vue project. I'm getting the following error.
> 
> **Try `npm install @types/jarallax` if it exists or add a new declaration (.d.ts) file containing `declare module 'jarallax';`**
> 
> I tried to do the steps mentioned in the following url but couldn't find the index.d.ts in node_modules.
> 
> [Add TypeScript support ](https://github.com/nk-o/jarallax/pull/91#issuecomment-408668356)
> 
> ### Version used:
> 1.12.0
> 
> ### Code to reproduce the issue (HTML blocks +TypeScript initialization)
> ```
>     <div class="jarallax">
>       <img class="jarallax-img" ssrc="..\assets\images\slider\IMG_7509-2.jpg" alt />
>       Your content here...
>     </div>
> ```
> 
> ```ts
> import { jarallax, jarallaxElement, jarallaxVideo } from "jarallax";
>    jarallax(document.querySelectorAll(".jarallax"), {
>       speed: 0.2
>     });
> ```

**Comment by nk-o** [comment]
Most probably this PR solved the issue - https://github.com/nk-o/jarallax/pull/199

I don't know, because I don't use typings in any of the projects. If anyone has a solution, feel free to make PR.
