### ISSUE TITLE
Jarallax Element - destroy method not available?

### ISSUE THREAD

**Issue by adstr123** [nk-o/jarallax#166]
Are the methods listed in the readme not applicable to instances of Jarallax Element rather than backgrounds?

I want to add the effect when an element is visible (detected with IntersectionObservers) and remove it when it is not visible. For performance reasons.

**Comment by nk-o** [comment]
Destroy method is working for Elements. If you have a non-working example, please, provide it using https://codepen.io/

**Comment by adstr123** [comment]
Hi @nk-o , my apologies. I made a mistake whilst reading the documentation!

I was targeting the incorrect element with the destroy method. I will close this issue.
