### ISSUE TITLE
Video volume not working with vimeo

### ISSUE THREAD

**Issue by AdelDima** [nk-o/jarallax#170]
Hello,

I just find when I use `data-video-volume="0"` on a video background it will work on youtube but not with Vimeo.
Here is an example:
https://codepen.io/AdelDima/pen/vYNjWje

**Comment by nk-o** [comment]
Unfortunately, you can't use unmuted videos on backgrounds https://github.com/nk-o/jarallax/issues/142#issuecomment-476538445

**Comment by AdelDima** [comment]
@nk-o Thank you for your replay, it just works on youtube this that makes me asking here.
