### ISSUE TITLE
Preview Image an black screen with loop on Youtube Videos

### ISSUE THREAD

**Issue by dimizu** [nk-o/jarallax#171]
### Issue description:
I have 2 issues with YouTube Videos and loop (not with self hostet videos!):
1 issue: first loop: the video and audio work fine. After the first loop, also when the second loop starts, the preview image is displayed constantly, and I cannot see the video. But the video plays because I can hear the audio.
2 issue: from the first loop to the second loop I see for approximately 0.5 seconds a black screen.

### Version used:
Version : 1.12.1

### Code to reproduce the issue (HTML blocks + JavaScript initialization)
Please see the code from here: [https://metek.com/landing/test/test.php](https://metek.com/landing/test/test.php)

**Comment by nk-o** [comment]
Issues with autoplay video+audio will not be fixed. Reason - https://github.com/nk-o/jarallax/issues/128#issuecomment-431428947

**Comment by dimizu** [comment]
The problems I wanted to describe are not autoplay and audio, but video loop problems only on youtube videos. My mistake, I gave you an example with audio. 

Here is an example with videoVolume:0: [https://metek.com/landing/test/test-noaudio.php](https://metek.com/landing/test/test-noaudio.php)

Autoplay ist not my problem (I know the restrictions from https://developers.google.com/web/updates/2017/09/autoplay-policy-changes)

The problems are with videoLoop: true (only on YouTube Videos!):
a) with YouTube videos and videoLoop: true on the transition from first loop to second loop I see an black screen
b) on the second loop the video is covered by the preview image (the video in the background plays but ist covered by the preview image)

This are the problems...

Workaround for b)
`.jarallax > div > div {
 display:none!important;
}`

But naturaly this is not ideal an remains the problem with the black screen from first to second loop...
