### ISSUE TITLE
Vimeo Mute/UnMute do not works

### ISSUE THREAD

**Issue by MaksymJ** [nk-o/jarallax#172]
hi,

thank you very much for this amazing plugin.
Vimeo Mute/UnMute do not work - https://codepen.io/looR/pen/VwvROEe
Youtube works, self-hosted mp4 also works, but Vimeo do not.

Best Wishes,
Maksym

**Comment by nk-o** [comment]
Hey.  
  
Yes, something wrong with Vimeo. Added Vimeo video for testing purposes here - https://codepen.io/_nK/pen/GQyvdZ?editors=1010
