### ISSUE TITLE
Vimeo shows pause button on scroll

### ISSUE THREAD

**Issue by sourcejockey** [nk-o/jarallax#175]
### Issue description:
When scrolling a page with a Vimeo background, it briefly shows the "pause" button over the video.

### Version used:
1.12.1

**Comment by nk-o** [comment]
Hey.

I'm not sure it can be fixed somehow. Jarallax automatically pauses videos, when not in the viewport, and Vimeo displays the pause button automatically.

**Comment by sourcejockey** [comment]
Hm--it seems to do it even when the video is in the viewport.

https://rotaryla5.org

**Comment by nk-o** [comment]
Looks like I understand the problem. You should be Plus, PRO, or Business member.

We use `background` option from Vimeo API https://github.com/vimeo/player.js/#embed-options

> Enable the player's background mode which hides the controls, autoplays and loops the video (available to Plus, PRO, or Business members).

**Comment by sourcejockey** [comment]
We actually have a PRO account--as well as "background=1" in the URL for the video. Is there a chance that it's not being passed?

**Comment by nk-o** [comment]
@sourcejockey which version of Jarallax do you use? Is it the latest?

**Comment by sourcejockey** [comment]
Ahhh, that was it. We were using 1.11.1 (installed in late June). Updating to the latest version did the trick. Thank you!
