### ISSUE TITLE
YouTube Video Sometimes fails to play with Uncaught TypeError: c.done is not a function

### ISSUE THREAD

**Issue by EmperorKonstantin** [nk-o/jarallax#178]
### Issue description:
YouTube Video Sometimes fails to play (even though the other videos on the page start playing with no issues) with

jarallax-video.js:1044 
Uncaught TypeError: c.done is not a function
    at i.value (jarallax-video.js:1044)
    at i.value (jarallax-video.js:658)
    at s.t.onScroll (jarallax-video.js:1112)
    at s.value (jarallax.js:697)
    at jarallax-video.js:1318
    at Image.n.onload (jarallax-video.js:610)
    

### Version used:
(Did you try using the develop branch from GitHub? There's a chance your issue has already been addressed there)

### Code to reproduce the issue (HTML blocks + JavaScript initialization)
```html
        <div class="jarallax jarallax-video" data-jarallax-video="https://www.youtube.com/watch?v=T5u9hdDyxeU">
            <h2>Example</h2>
        </div>
```

```javascript
<script>
    jarallax(document.querySelectorAll('.jarallax'), {
        loop: true,
        videoStartTime: 30,
    });
</script>
```

**Comment by nk-o** [comment]
Created a Codepen example. I don't see the error, but the loop is not working here for some reason.

https://codepen.io/_nK/pen/YzqXNKg

**Comment by EmperorKonstantin** [comment]
Thanks  bud, works fine now again!
