### ISSUE TITLE
Destroy on mobile devices

### ISSUE THREAD

**Issue by davydkoff** [nk-o/jarallax#18]
Hello! How to destroy Jarallax on windows phone or any others mobile devices?

**Comment by nk-o** [comment]
Hi, davydkoff.

You can prevent initialization for mobile devices. This is not possible with data-attribute way, only with JS or jQuery.

Found mobile check code here - http://stackoverflow.com/questions/3514784/what-is-the-best-way-to-detect-a-mobile-device-in-jquery

Example:
```javascript
var isMobile = /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent);

if(!isMobile) {
    $('.jarallax').jarallax();
}
```

**Comment by davydkoff** [comment]
Thank You!
