### ISSUE TITLE
Strange behaviors in macOS Big Surprise betas

### ISSUE THREAD

**Issue by elixirgraphics** [nk-o/jarallax#181]
### Issue description:
In all macOS Big Sur betas so far Jarallax seems to have strange behaviors in Safari v14.x.x -- parallax backgrounds leaving their divs, etc.

The example pages for Jarallax show some of these problems in Safari v14.x.x on macOS Big Sur public beta:

https://wpbackgrounds.com

https://free.nkdev.info/jarallax/

**Comment by elixirgraphics** [comment]
This is also happening in the non-beta version of Safari v14 that launched today.

**Comment by liefra** [comment]
I'm seeing the same strange behaviour also on the iPadOS Safari version.

**Comment by NazarkinRoman** [comment]
+1 https://imgur.com/iVPnrAG

**Comment by castellaniperez** [comment]
Same bug here...

**Comment by nk-o** [comment]
@castellaniperez https://github.com/nk-o/jarallax/releases/tag/v1.12.3
