### ISSUE TITLE
Video Poster Option

### ISSUE THREAD

**Issue by especdevelopment** [nk-o/jarallax#185]
Firstly...I LOVE this package! Thank you for the continued support of it!

I am curious if you have ever considered adding a video poster option. I am sure I could handle this via my own html/css but I was thinking it could be very helpful to have the option of adding a video poster image so that the videos (especially self-hosted) can have a poster element (or a fill-in for poster) that can display prior to the video loading. 

Just thought I would throw that out into the universe. Thanks again and great work! :)

**Comment by nk-o** [comment]
Hey.

You just need to set an image as if you use image parallax. https://github.com/nk-o/jarallax#set-up-your-html
