### ISSUE TITLE
Pattern bg

### ISSUE THREAD

**Issue by davydkoff** [nk-o/jarallax#19]
Is it possible to use a looped pattern background instead of a full-size image?

**Comment by makshh** [comment]
For patterns, I use this code:

`<div data-jarallax='{"speed": -0.25}' class="jarallax jarallax-pattern" style="background-image: url(yourpattern.png); height: 500px;"></div>`


```
.jarallax-pattern {
  background-size: auto !important;
  background-repeat: repeat !important;
.jarallax-pattern div > div {
  background-size: auto !important;
  background-repeat: repeat !important;
  background-position: 0% 0% !important;
}

```

**Comment by davydkoff** [comment]
**makshh**, Thank You! It works for me!

**Comment by davydkoff** [comment]
Oh! How about tag <img> in Microsoft Edge? It does not work, unfortunately...

**Comment by nk-o** [comment]
I'll thinking and maybe this feature will be implemented in future releases.
