### ISSUE TITLE
How to disable jarallax only for safari Mac OS

### ISSUE THREAD

**Issue by E-Baler** [nk-o/jarallax#196]
Hello, sorry if I'm wrong posting here a question but I don't find the solution (I'm a dev beginner) 😔 

Jarallax doesn't work well on Safari Mac OS - but works great on other browser. I would like to disable jarallax only for safari Mac OS but I don't find How to do it. What is regular expression for specific user agents as said in the description of jarallax please?

Thanks a lot and sorry for my english ;)

**Comment by nk-o** [comment]
Hey.

This one should work:

```
disableParallax: /^((?!chrome|android).)*safari/i
```
