### ISSUE TITLE
Simple  question

### ISSUE THREAD

**Issue by BackuPs** [nk-o/jarallax#2]
The video demo has errors in the error console

http://free.nkdev.info/jarallax/video-parallax.html

Same and Different ones in Firefox and Chrome

**Comment by BackuPs** [comment]
i adjusted my question.

**Comment by BackuPs** [comment]
Can you also please add horizontal parallaxing?

**Comment by nk-o** [comment]
@BackuPs no, horizontal scrolling is not planning. But feel free to make pull request.
Most of errors in video demo are from Youtube and Vimeo. But there is some from jarallax - they will be fixed.
