### ISSUE TITLE
add async support

### ISSUE THREAD

**Issue by broros** [nk-o/jarallax#202]
### Issue description:
does not work with ASYNC in javascript

### Version used:
1.12.8

### Code to reproduce the issue (HTML blocks + JavaScript initialization)
  <script src="../dist/jarallax.js" async></script>

**Comment by nk-o** [comment]
I hope this one could help - https://css-tricks.com/snippets/javascript/async-script-loader-with-callback/
Or use data-attribute initialization https://github.com/nk-o/jarallax#a-data-attribute-way
