### ISSUE TITLE
Replace deprecated Vimeo Simple API usage

### ISSUE THREAD

**Issue by sergiy-v** [nk-o/jarallax#205]
### Issue description:
The deprecated Vimeo Simple API (https://vimeo.com/api/v2/video/) uses to get video metadata (image), [reference](https://github.com/nk-o/jarallax/blob/master/dist/jarallax-video.js#L495).
You can find more details about Deprecated Vimeo APIs [here](https://vimeo.zendesk.com/hc/en-us/articles/360042975791-Deprecated-APIs-libraries-and-upload-methods).
As mentioned in the article the [oEmbed implementation](https://developer.vimeo.com/api/oembed) should be used instead of deprecated API.
It would be good to replace deprecated Vimeo Simple API usage to avoid any issue in future.

### Version used:
v1.12.8.

**Comment by nk-o** [comment]
Fixed in v2.0.1

**Comment by sergiy-v** [comment]
Awesome, thank a lot)
