### ISSUE TITLE
Image is not changing when used picture tag on resize, its working only for page reload

### ISSUE THREAD

**Issue by VenkatNiranjan** [nk-o/jarallax#212]
### Version used:
(Did you try using the develop branch from GitHub? There's a chance your issue has already been addressed there)

### Code to reproduce the issue (HTML blocks + JavaScript initialization)
```html

```

```javascript

```

**Comment by nk-o** [comment]
Working with no problem https://codepen.io/_nK/pen/VwxpPoz
