### ISSUE TITLE
Full screen image

### ISSUE THREAD

**Issue by makshh** [nk-o/jarallax#22]
Hi @nk-o,

I have an issue with combining Jarallax with Royal Slider.

I think this is not an Jarallax issue, but maybe you can help me.

I'm using this code to change width and height of the slider:

Everything works good, but when I resize my browser image doesn't always match the height and width of the window when I'm using Jarallax.

Without slider it works fine.

![GIF](http://i.giphy.com/wYbxRp0XS5rSE.gif)

**Comment by nk-o** [comment]
Hi, @makshh.

It seems like RoyalSlider used small timeout after window resize and then changed slider size. I think you can use event from RoyalSlider api that fires when slider is resized. I don't actually know their api, but this example should work if this event exists:

```javascript
var $jarallax = $('.jarallax').jarallax();
$('.my-slider').on('slider-resized', function () {
    $jarallax.jarallax('coverImage');
    $jarallax.jarallax('clipContainer');
    $jarallax.jarallax('onScroll');
});
```
