### ISSUE TITLE
Module '"jarallax"' has no exported member 'jarallaxVideo'.

### ISSUE THREAD

**Issue by Super-Kenil** [nk-o/jarallax#226]
### Issue description:
Typescript Error when importing jarallaxVideo

### Version used:
v.2.2.0

The Error which I am mentioning here has already been fixed in this PR #224 

But, the latest code from `master` branch is not published on npm.
Only thing the author needs to do is publish the latest code from master branch on npm

**Comment by nk-o** [comment]
Please, update to v2.2.1

**Comment by Super-Kenil** [comment]
Thanks for publishing the new update
