### ISSUE TITLE
iPhone 7 parallax scrolling not smooth

### ISSUE THREAD

**Issue by nrezane** [nk-o/jarallax#24]
Good day,

I used the WordPress plugin but I found out on iphone 7 the parallax scrolling for mobile is not smooth. Is there a quick fix for it?

Thank you.

**Comment by nk-o** [comment]
Hi.

No, unfortunately, there is no quick fix for it. We need to completely rethink the code for mobile devices, but they are all the same will not work as smoothly as in the native mobile apps.
