### ISSUE TITLE
Jarallax loaded by ajax

### ISSUE THREAD

**Issue by chladog** [nk-o/jarallax#26]
Hello,
I'm having problem with ajax loaded jarallaxes. http://publisalfa.publis.cz/all-works/
After scrolling to the bottom of the page, new items are loaded and jarallax init is called, loaded items are working right way, but previous items backgrounds have wrong vertical position, not filling container elements properly.
Is it possible to use dynamically loaded jarallaxes?

**Comment by nk-o** [comment]
Hey.

Your AJAX script reloads all available blocks. Do it properly, only load new blocks and don't touch existing ;)

Best regards, nK.
