### ISSUE TITLE
Parallax speed video can not be bigger then 1 or smaller then 0

### ISSUE THREAD

**Issue by BackuPs** [nk-o/jarallax#27]
Hi 

When parallax speed is below 0 or bigger then 1 the video background has issues.

**Comment by nk-o** [comment]
Hi.

I can't repeat this bug with the latest commits. Can you provide website URL where this happens?

**Comment by BackuPs** [comment]
after waiting for more then a month on getting a response to this i dumped the integration. I have to find the old files again and recreate a test build. I dont have it at hand now as it is more then 2 months ago and we needed to carry on.

**Comment by nk-o** [comment]
I was not able to repeat this error. For now I checked and my videos all are working fine.
Thank you for writing bug reports for Jarallax.

**Comment by BackuPs** [comment]
I found a backup.. 1st is the one with speed set to -.0.8 the second one  has speed set to 0.5

You will see that the video in the first goes only just about half of the screen in the first one.

http://jarallax.backupsdemo.nl/jarallax-video-issue/

**Comment by nk-o** [comment]
I fixed it yesterday. It is just because of **max-width** style for iframe:

![image](https://cloud.githubusercontent.com/assets/14810891/22696444/13109620-ed5f-11e6-889d-4712cee413ae.png)

For now jarallax added **max-width: none** on iframe on initialization.

**Comment by BackuPs** [comment]
That fixes the issue. Thanks for the code fix. You can close this one.

**Comment by BackuPs** [comment]
Does mute on of work???  It did before it does not with the latest build.  I turned OFF mute but no sound!

**Comment by nk-o** [comment]
Mute was fixed, but I don't create a new version of plugin yet. https://github.com/nk-o/jarallax/commit/dbd73c9a6d8ed812831ba3d2ec72feacf914dcdd

**Comment by BackuPs** [comment]
ok !
