### ISSUE TITLE
How To Mute a local hosted video?

### ISSUE THREAD

**Issue by BackuPs** [nk-o/jarallax#28]
Hi

A local hosted video is not muted.  How to achieve this?

Best regards,
BackuPs

**Comment by davydkoff** [comment]
Hello! Try this code:

`<video controls muted>
  <source src="movie.mp4" type="video/mp4">
  <source src="movie.ogg" type="video/ogg">
  Your browser does not support the video tag.
</video>`

**Comment by BackuPs** [comment]
Hi Davyd

Thanks for the solution... but i am talking about the jarallax video script which creates the video tag on the fly for local hosted videos and adds a attribute muted="on" to the tag as well as loop="on"

I know how to add the  muted for the video tag and thus muted the video. But that is besides the point which is that the video script does not do it out of the box.

It mutes the youtube and vimeo video but not the self hosted one. So if you want a parallaxing video and the video has audio it does not mute the sound.

Best regards,B

**Comment by nk-o** [comment]
Hi.

Mute for local videos is fixed in 1.7.2 version. Please, update the script and let me know.

https://github.com/nk-o/jarallax/releases

**Comment by BackuPs** [comment]
Hi

I am and was using version 1.7.2 before posting this thread and it does not mute the local video at all. i had to change the code to

`                    if(_this.options.mute) {
                        _this.$iframe.setAttribute('muted', 'on');
			_this.$iframe.muted=true;
                    }
`

to get it to work.
