### ISSUE TITLE
Local Video Not Working

### ISSUE THREAD

**Issue by d3haynes** [nk-o/jarallax#30]
Youtube and Vimeo work fine, however local videos do not. 

I have tried this multiple ways - currently using the data attribute. Looking at your getLocalVideos function, result gives me the object with my video paths for different types, but returns nothing in the ternary. if I just return result, I get a value but the if/else to set this.type fails - I never get this.type set to "local" even though Local (getLocalVideos()) has a value.

**Comment by nk-o** [comment]
Can you provide URL with non-working local videos? Also, see here example that works fine on demo page https://github.com/nk-o/jarallax/blob/master/demo/index.html#L69

**Comment by d3haynes** [comment]
hi @nk-o , absolutely!

[http://d32016.d3proof.com/who-we-are](http://d32016.d3proof.com/who-we-are)

You can see that I am using the data attribute, and if you check the console I am logging the object that is built in the getLocalVideos() function.

I see the demo works well, which is why I am at a loss for what could be going wrong. In my debugging, my above findings is where the trail ends....


thanks!

**Comment by nk-o** [comment]
You have set relative URL and browser trying to grab your video from here:
**http://d32016.d3proof.com/who-we-are/media/video/Busy-People.mp4**

You need to set absolute URL or full URL (starting from http://...).

You set:
**/media/video/Busy-People.mp4**

Need:
**./media/video/Busy-People.mp4**

Or:
**ht<span></span>tp://d32016.d3proof.com/media/video/Busy-People.mp4**

**Comment by d3haynes** [comment]
hmm I have tried both of those - you can refresh that page and see that I am trying ./media/video/Busy-People.mp4. I have tried the absolute url as well.

**Comment by nk-o** [comment]
I found what the problem. Local video is not working if you not added image background.

In this way:
```
<div class="jarallax" style="background-image: url(video/local-video.jpg);" data-jarallax-video="mp4:http://d32016.d3proof.com/media/video/Busy-People.mp4"></div>
```

It will be fixed in the next update. Thank you.

**Comment by d3haynes** [comment]
thanks!

**Comment by webberwang** [comment]
Getting this as well, hopefully fixed soon!
