### ISSUE TITLE
Set Options

### ISSUE THREAD

**Issue by wassereimer86** [nk-o/jarallax#31]
Hi,

i call your great plugin gloabal by the jQuery way inside of another plugin wich lazy loads everything. Working fine.

$('.jarallax').jarallax();

But how am i able to set, for example, another speed for only one jarallax? If im doing it like the following the parallax doesn´t work and i have a image thats not moving.

<div data-jarallax='{"speed": 0.2}' ......

Best regards
wassereimer

**Comment by nk-o** [comment]
Hi.

You can add data-attributes, but if you added speed options in JavaScript initialization code, speed form data attribute will not be used.

Also, you can try to add your own attribute. Example:

```
<div class="jarallax"></div>
<div class="jarallax" data-my-speed="0.5"></div>
```
```
var defaultSpeed = 0.1;
$('.jarallax').each(function () {
   $(this).jarallax({
      speed: parseFloat($(this).attr('data-my-speed')) || defaultSpeed
   })
});
```

Best regards, nK.

**Comment by wassereimer86** [comment]
Hi,

your example with an own data attribute is working, thank you. :)

General: Whats the best way to call the plugin and handle the options? As i said i use a lazy loading script (https://github.com/dinbror/blazy) and call it within the callback function (http://dinbror.dk/blog/blazy/?ref=github#Callback). Is there a better way or what would you suggest?

Best regards
wassereimer

**Comment by nk-o** [comment]
You're doing it in the right way 👍

**Comment by wassereimer86** [comment]
Thank you for your help and your great work on the script. :)
