### ISSUE TITLE
Jarallax after lazy loading

### ISSUE THREAD

**Issue by wassereimer86** [nk-o/jarallax#32]
All images on my site are loaded with lazy loading. I use this script for it: https://github.com/dinbror/blazy

Everytime a images is successfully lazy loaded i call jarallax. Because its possible that the image should have the parallax effekt.

```
    ;(function() {
        var bLazy = new Blazy({
        success: function(ele){
          	console.log("bLazy success");
          	if ($(ele).hasClass("gojarallax")) {
        		$(ele).addClass("jarallax");
                	$(ele).removeClass("gojarallax");
            		$('.jarallax').jarallax();
                	console.log("bLazy jarallax success");
        	}
        },
```

Thats the part which is interesting.

Now i have the problem that sometimes is an image and other content on the jarralax container but the image inside the container is loaded after the jarallax call. The timeline is this:

-> background image which should have parallax is lazy loaded
-> jarallax is called
-> image inside the jarallax container is loaded

The problem is that the parallax in this case doesn´t fill the complete container and i have blank space in the exact size of the image which is inside the container. How can i solve this?

I tried to call clipContainer and coverImage this way

```
    ;(function() {
        var bLazy = new Blazy({
        success: function(ele){
          	console.log("bLazy success");
          	if ($(ele).hasClass("gojarallax")) {
        		$(ele).addClass("jarallax");
                	$(ele).removeClass("gojarallax");
            		$('.jarallax').jarallax();
            		$('.jarallax').jarallax('METHODNAME');
                	console.log("bLazy jarallax success");
        	}
        },
```

But it doesn´t work.

**Comment by wassereimer86** [comment]
Got it. God damn. Tried for hours and after this post i find it..... ^^

clipContainer is working. But it has to be outside the `if ($(ele).hasClass("gojarallax")) {`

**Comment by wassereimer86** [comment]
I know this is closed now, but can you perhaps take a look at my last question? :)

"What is the exact different between clipContainer and coverImage ? coverImage isn´t working but clipContainer is."

**Comment by nk-o** [comment]
These are different functions, you should run **both**, not only clipContainer.

See sources to get more info what exactly doing these functions:
**coverImage**: https://github.com/nk-o/jarallax/blob/master/jarallax/jarallax.js#L420
**clipContainer**: https://github.com/nk-o/jarallax/blob/master/jarallax/jarallax.js#L386

Here is example when they are called (on window resize): https://github.com/nk-o/jarallax/blob/master/jarallax/jarallax.js#L639

**Comment by wassereimer86** [comment]
Thank you very much for the links and help. :)
