### ISSUE TITLE
Local Video Parallax not play on Mobile

### ISSUE THREAD

**Issue by ashanrupasinghe** [nk-o/jarallax#33]
I used local video on my client's website, That works fin in desktop but in mobile, not play the video.
If I set Youtbue or Viemo link, they also work fine. What happened to local video?
How can I fix the issue.

**Comment by nk-o** [comment]
For me videos are not working on mobile devices (Youtube and Vimeo also). I think need some code fixes to make it working,

**Comment by ashrafreda** [comment]
Is this issue fixed? 
All videos (Youtube, Vimeo) not working (not just parallax effect but the video background don't display on mobile), despite disabling parallax effect on mobile.
`$parallax.jarallax({
			noAndroid: true,
			noIos: true,
    });`

**Comment by ashrafreda** [comment]
hi Nikita,
will you fix this issue soon?

**Comment by nk-o** [comment]
Hi, @ashrafreda.

I tested Youtube and Vimeo autoplay videos (not as background, just plain <iframe> on the page). And autoplay is not working on mobile devices.
Autoplay only works with local videos in the <video> tag.

So, we need to wait for the Youtube and Vimeo mobile compatibility and then I'll check it with Jarallax.
