### ISSUE TITLE
Horizontal Scroll

### ISSUE THREAD

**Issue by enkhtulga** [nk-o/jarallax#34]
Hi,

First of all, thank you for doing this awesome javascript.

I would like to use jarallax in horizontal scroll. Is there some option for it?
NOW:  from TOP to BOTTOM scroll
I WANT: from LEFT to Right scroll ?

Thank you,
Enkhtulga.G

**Comment by nk-o** [comment]
Hi, Enkhtulga.

No, Jarallax is working only with vertical scroll. I think horizontal scrolling will be never implemented in plugin code, but you can make extension and make pull request.

Best regards, nK.

**Comment by enkhtulga** [comment]
Thank you for your response.

I am using Mouse Wheel jQuery plugin --> https://css-tricks.com/snippets/jquery/horz-scroll-with-mouse-wheel/

If you have some idea then please share with me. :)

Thank you,
Enkhtulga.G

**Comment by ahmetsali** [comment]
> Hi, Enkhtulga.
> 
> No, Jarallax is working only with vertical scroll. I think horizontal scrolling will be never implemented in plugin code, but you can make extension and make pull request.
> 
> Best regards, nK.

Hi, thanks for this great plugin, I have just came across another parallax plugin with orientation option which allows to have horizontal parallax, on the demo it looks very cool;

https://simpleparallax.com/

I would love to see this feature in the amazing jarallax plugin :)

Have a nice day!
