### ISSUE TITLE
Jarallax on Slick Slider

### ISSUE THREAD

**Issue by aydinvivik** [nk-o/jarallax#35]
Is it possible to use Jarallax in SlickSlider?

**Comment by aydinvivik** [comment]
Hello there,
I tested, it works fine but i'm having a problem with responsive settings. (http://prnt.sc/esd0qp)

1900px on desktop : http://prnt.sc/esd1at
969px : http://prnt.sc/esd1ee

help me.

**Comment by nk-o** [comment]
Hi.

It is possible, but I have never tried this. See here theme, that used OwlCarousel with Jarallax - [http://demo.codesupply.co/authentic/](http://demo.codesupply.co/authentic/)

I think it required additional coding, that I don't provide.

Best regards, nK.

**Comment by aydinvivik** [comment]
Yes thanks, i saw. I will be very happy if I can solve this problem. Do you have any ideas for solving the problem?

**Comment by nk-o** [comment]
Have no idea.
