### ISSUE TITLE
parallax on absolute positioning

### ISSUE THREAD

**Issue by smatsa65** [nk-o/jarallax#42]
In my site a menu is pushing the main page to the right as it enters the view oft the user. 
The main page contains various jarallax sections (mainly images). To slide the main section in and out of view I had to set its position to absolute. Changing the position from static to absolute however, will cause all jarallax powered sections to loose position and (re-)size of its contents.

1. Is there a workaround in a way that jarallax also works on absolute positioned elements?
2. Alternatively, how could I make use of “**parallax section client rect**” to position these contents with javascript while absolute and return to be jarallax-controlled as soon as they become static again?

**Comment by nk-o** [comment]
Could you provide url to your page, where you implemented this feature.

**Comment by smatsa65** [comment]
I was experimenting with it on localhost. But here I have auploaded the code to [www.mildlemon.com](www.mildlemon.com). When opening the menu (pushing the main content to the right) I detsroy the jarallax object. Before doing that I would need to get the coordinates from jarallax to position the image with css so that it keeps its position unchanged.

**Comment by nk-o** [comment]
I see you creating &lt;div> for the content every time when you trying to open menu. It is a bad solution.

I just created an example for offcanvas menu + jarallax. See it here - [https://codepen.io/_nK/pen/pwyPZE](https://codepen.io/_nK/pen/pwyPZE)

**Comment by smatsa65** [comment]
I appreciate your solution, but the problem with this approach is that the height of the menu cannot exceed the window height. Anything that overflows will be hidden from view.
I'm looking for a solution that uses the default scrollbars of the window to scroll down an expandable menu.

**Comment by nk-o** [comment]
Do you need this one?

![image](https://user-images.githubusercontent.com/14810891/27011800-6d8c8284-4ecc-11e7-97e8-5f1f0a317fba.png)

**Comment by smatsa65** [comment]
Thanks a lot for your help. I will try that one, though I would prefer to use the main scrollbar of the browser window. But probably your solution is the better one.
Still that question: can I get jarallax to return the exact size an postition of the background image?
I tried to play around with  console.log(calculations); but was not sure how to apply it to css-position the element.

**Comment by nk-o** [comment]
onScroll event return an actual size and position of jarallax block. It can help only when you use it with jarallax. Once you destroyed it, you will have, for example, background image with cover size, that is not the same like in jarallax block.

I think you can clone jarallax block and work with it.
![image](https://user-images.githubusercontent.com/14810891/27012254-1ebba596-4ed5-11e7-92ac-b59eb04513ce.png)
