### ISSUE TITLE
Too stretched background image

### ISSUE THREAD

**Issue by onmarketing** [nk-o/jarallax#45]
Hi,

It's very URGENT.

I have problem with background-image is too stretched, zoom in. I would like to have prefect background image size not too stretched if you know what I mean (see image)

```
<div class="jarallax h500" data-jarallax='{"speed": 0.2}' style="background-image: url(assets/images/header-2.jpg);">
    <div class="content-text text-white">
        <h1 class="mb-0">Social Media Courses</h1>
    </div>
</div>
```

How to make background image small not too big on parallax?

Does anyone know how do fix this problem?

Thanks,

Shaun.
![capture](https://user-images.githubusercontent.com/29661125/27682360-2a5904e6-5cba-11e7-9de8-d10007780002.PNG)

**Comment by volbil** [comment]
Also have this problem, any suggestion about it?

**Comment by nk-o** [comment]
Hi @onmarketing

Parallax backgrounds work with image like `background-size: cover` style doing this. So, this is normal behavior. If you need to show full image - don't use parallax.

**Comment by PubliAlex** [comment]
I have the same problem with standard parallax (no background), even with speed = 0.0001, the image get a big zoom, far too zoomed compared to the parallax need, and the image is pixellized.
