### ISSUE TITLE
videoStartTime and videoEtartTime

### ISSUE THREAD

**Issue by TiagoDeSousa** [nk-o/jarallax#46]
videoStartTime and videoEndTime only seem to work for Youtube videos. It doesn't seem to be working for Vimeo or local videos.

Using this method doesn't work:
$('.parallax').jarallax({
    speed: 0.2,
    videoStartTime: 128,
	videoEndTime: 150,
  });

however using this method seems to be fine:
data-jarallax='{"videoStartTime": 128, "videoEndTime": 150}'

**Comment by nk-o** [comment]
videoStartTime fixed for Vimeo.
Local videos are working fine for me. If you have an online example with non-working local videos, it would be good.
