### ISSUE TITLE
Browser compactibility

### ISSUE THREAD

**Issue by shovanjaya55** [nk-o/jarallax#47]
I'm working on my WordPress project to add the background image/videos for my plugin. What I'm seeing is very strange. The HTML5 video integration works fine for google chrome and opera but in the Firefox the html5 video is not appearing at all. The browser goes on loading and loading. Any one experiencing this type of problem? Am I the only one who is getting this error?

**Comment by nk-o** [comment]
@shovanjaya55 I don't have problems with Firefox videos. Any online examples will be helpful.
