### ISSUE TITLE
Custom Data set Returns Empty DataOptions

### ISSUE THREAD

**Issue by BackuPs** [nk-o/jarallax#5]
Hi

The solution given in this thread

https://github.com/nk-o/jarallax/issues/3

does not work. The dataOptions are empty. since the script reads them on the item.data('jarallax'):

dataOptions      = _this.$item.data('jarallax') || {};

Do you have a working solution?

Thank you
Best regards,
BackuPs

**Comment by BackuPs** [comment]
You try it please

`<div class="jarallax" data-myjarallax='{"type": "scale-opacity", "speed": 1.3, "imgWidth": 1366, "imgHeight":766, "enableTransform": false}' style="background-image: url(images/image1.jpg);height:600px;">
</div>`

    var isMobile = (/Android|iPhone|iPad|iPod|BlackBerry|Windows Phone/i).test(navigator.userAgent || navigator.vendor || window.opera);
	
if(!isMobile) {
    $('.jarallax').each(function () {
		console.log($(this).jarallax($(this).data('myjarallax')));
        $(this).jarallax($(this).data('myjarallax') || {});
    })
}


or

if(!isMobile) {
    $('.jarallax').each(function () {
		console.log($(this).jarallax($(this).data('data-myjarallax')));
        $(this).jarallax($(this).data('data-myjarallax') || {});
    })
}

**Comment by nk-o** [comment]
Hi, BackuPs.

This is working fine...

Demonstration Video:
[![Demonstration Video](https://img.youtube.com/vi/Cr0OCAjpq08/0.jpg)](https://www.youtube.com/watch?v=Cr0OCAjpq08)

To show data object in the console, use it:
```
console.log($(this).data('data-myjarallax'));
```

Best regards, nK.

**Comment by BackuPs** [comment]
Hi

Yes..... it does but i had 3 different datatypes and then it does not work. as you can only use this once

$(this).jarallax($(this).data('themejarallax') || {});

and not for each element 


$(this).jarallax($(this).data('smartboxjarallax') || {});
$(this).jarallax($(this).data('sectionjarallax') || {});

i had it like this

    jQuery('.smart_box').each(function() {
        if ($(this).hasClass('jarallax')) {
            if (!isMobile) {
				 $(this).jarallax($(this).data('smartboxjarallax') || {});
                }
		}
    });
    jQuery('.theme_section').each(function() {
        if ($(this).hasClass('jarallax')) {
            if (!isMobile) {
				 $(this).jarallax($(this).data('data-section-jarallax') || {});
                }
		}
    });

and that does not work.

**Comment by nk-o** [comment]
`$(this).data('data-section-jarallax')` should be -> `$(this).data('section-jarallax')`

**Comment by BackuPs** [comment]
i had a type above by not having the '-' sorry about that but it  does not work when you have more then one different data type name 

I had to give them all the same name to get it working.

**Comment by nk-o** [comment]
I think you doing something wrong. Because what you trying - is not Jarallax problem. You just got the DOM element, got the parameters, and give it to the plugin. So, if you give wrong parameters - plugin will work with this wrong parameters.

I tried it and it working for me perfectly:
```
if (!isMobile) {
    $('[my-cool-parameters]').each(function() {
        $(this).jarallax($(this).data('my-cool-parameters') || {});
    }
    });
    $('[my-extremely-best-parameters]').each(function() {
        $(this).jarallax($(this).data('my-extremely-best-parameters') || {});
    });
}
```

Plus I don't understand why do you want different data attributes for SINGLE plugin.

**Comment by BackuPs** [comment]
Hi

so this works for you?

<div class="jarallax" data-themejarallax='{"type": "scale", "speed": 1.3, "imgWidth": 1366, "imgHeight":766, "enableTransform": false}' style="background-image: url(images/image1.jpg);height:600px;">
</div>
<div class="jarallax" data-mythemejarallax='{"type": "scale", "speed": 1.3, "imgWidth": 1366, "imgHeight":766}' style="background-image: url(images/image1.jpg);height:600px;">
</div>


    var isMobile = (/Android|iPhone|iPad|iPod|BlackBerry|Windows Phone/i).test(navigator.userAgent || navigator.vendor || window.opera);
    var $ = jQuery;

	
if(!isMobile) {
    $('.jarallax').each(function () {
        $(this).jarallax($(this).data('themejarallax') || {});
    });
    $('.jarallax').each(function () {
        $(this).jarallax($(this).data('mythemejarallax') || {});
    });
}


in my case the second one scrolls. and i cant seem to find the mistake i am making. I am missing it.

**Comment by nk-o** [comment]
Let's try to clarify it for you.

1) You init plugin:
 ```
$('.jarallax').each(function () {
    $(this).jarallax($(this).data('themejarallax') || {});
});
```
2) ALL blocks with **.jarallax** classname got their parallax effect.
3) You try to init it again:
 ```
$('.jarallax').each(function () {
   $(this).jarallax($(this).data('mythemejarallax') || {});
});
 ```
4) Nothing happens, because Jarallax currently inited.


Working example of your code:
```
$('.jarallax').each(function () {
    $(this).jarallax($(this).data('themejarallax') || $(this).data('mythemejarallax') || {});
});
```

**Comment by BackuPs** [comment]
Hi

That was my mistake.... Thank you. Still learning on the jquery ... pffff

Great support you give !

Best regards,
BackuPs
