### ISSUE TITLE
jarallax not init on ios device

### ISSUE THREAD

**Issue by aliwaqassi** [nk-o/jarallax#59]

**Comment by nk-o** [comment]
Maybe **noIos** option will help. By default it set to **true**, you need to change it to **false**.

See here how to call the plugin with your options https://github.com/nk-o/jarallax#call-the-plugin.
Here the list of available options - https://github.com/nk-o/jarallax#options

**Comment by aliwaqassi** [comment]
Thanks 
but there is an origin problem with youtube video in iphone and i pad

**Comment by nk-o** [comment]
@aliwaqassi I think it was fixed in the latest update. Please, check it and let me know if you have problems with it.
