### ISSUE TITLE
Jarallax only for static element - not background.

### ISSUE THREAD

**Issue by vertisan** [nk-o/jarallax#6]
Hi!
Your library is really great, but I have one question - how  can I set this effect for normal element without background?
I want do somethink like you have in header on your project ( http://wp.nkdev.info/youplay/ )

**Comment by nk-o** [comment]
Hi, vertisan.

It's more like a _hack_, not a normal solution.

Example:
```
$('.jarallax').each(function () {
    var $content_item = $(this).find('.my-content');

    $(this).jarallax({
        type: 'custom',
        imgSrc: 'data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7',
        imgWidth: 1,
        imgHeight: 1,
        onScroll: function (calculations) {
            // scroll on 150px
            var scrollContent = Math.min(150, 150 * (1 - calculations.visiblePercent));

            $content_item.css({
                opacity: calculations.visiblePercent,
                transform: 'translate3d(0, ' + scrollContent + 'px, 0)'
            });
        }
    });
});
```
You can see _calculations_ variable description here - https://github.com/nk-o/jarallax#onscroll-event

p.s. I think this is solution for issue #1
