### ISSUE TITLE
Jarallax youtube video origin problem

### ISSUE THREAD

**Issue by aliwaqassi** [nk-o/jarallax#60]

**Comment by nk-o** [comment]
Could you please give me more information? Online demo will be fine.

**Comment by aliwaqassi** [comment]
Here is my example
<div class="jarallax" data-jarallax-video="https://www.youtube.com/watch?v=k_okcNVZqqI?rel=0" style=""></div>

this is working on desktop and anroid
in ios and ipad there is an origin error
Blocked a frame with origin "https://www.youtube.com" from accessing a frame with origin "http://28281503909791.appon.io".  The frame requesting access has a protocol of "https", the frame being accessed has a protocol of "http". Protocols must match.

**Comment by nk-o** [comment]
I can't repeat this type of error on my local machine and on the server. Checked on iPhone with iOs10 and beta 11.

I definitely need your online example.

**Comment by aliwaqassi** [comment]
here is my example
http://waqaspreview.appon.io/

**Comment by nk-o** [comment]
Can't see errors here in iOs simulator:
![image](https://user-images.githubusercontent.com/14810891/30324954-820b0be8-97cb-11e7-81b5-9efe0229fd8c.png)

**Comment by aliwaqassi** [comment]
hmmm.
when i hit this example in iphone it shows video thumbnail not playing video

**Comment by nk-o** [comment]
Yes, because Youtube doesn't support video autoplay on mobile devices.

**Comment by aliwaqassi** [comment]
So if i upload youtube video on my server and i play as a local video. will it work?

**Comment by nk-o** [comment]
No, autoplay on mobile devices will not work. I think it is supported by browsers, but I don't check.

**Comment by aliwaqassi** [comment]
hmm Thanks bro
Closed issue
