### ISSUE TITLE
How can i use it in a slider without it setting the others slides to 100, 100 rectangle

### ISSUE THREAD

**Issue by schroef** [nk-o/jarallax#61]
Im using a version which is 1.0 and comes with Mobirise website builder. I tried hacking a forced resize in but didnt get the wanted result. Though the size of the other slides are adjusted, now the position of the other is weird.

Only when i resize the window, the current active slides is adjusted. Other slides get wrong ratio or are mask to a rect (0,100,100,0)

**Comment by nk-o** [comment]
Hi.

You should use **elementInViewport** option to make parallax working in carousels. Discussion about this option you can find in #13 

Ask for Mobirise developers to updated Jarallax and fix the problem. I think they'll fix it quickly.

**Comment by schroef** [comment]
Thanks for pointing out that comment. I'll check and see if i can get it to work now.
Mobirise uses different classes, special class i guess. I tried using the same code from a example scene in the master, didnt got expected results. Even with same code and correct new js source.

Ill check and see what is wrong. My guess the css
