### ISSUE TITLE
Call jarallax on target click

### ISSUE THREAD

**Issue by schroef** [nk-o/jarallax#64]
I cant remember how i can call a forced jarallax check. I think i did it a couple weeks ago but cant remember what code i put. 

I want to init jarallax in a section when a accordion is opened. Now the jarallax div only resize when window is resized.

**Comment by nk-o** [comment]
Hi.

To force jarallax recalculation you need to call 3 methods:

```javascript
var $jarallax = $('.jr').jarallax();

$jarallax.jarallax('coverImage');
$jarallax.jarallax('clipContainer');
$jarallax.jarallax('onScroll');
```
