### ISSUE TITLE
Resize on mobile

### ISSUE THREAD

**Issue by datune** [nk-o/jarallax#69]
Is there any way to prevent the background image from resizing when the browser viewport changes? It happens a lot on mobile, since on iOS for example, once you start scrolling, the top menu dissapears, which then triggers a resize and makes everything look "jittery" if you know what I mean. You can use your own demo page to verify this behaviour.

**Comment by nk-o** [comment]
Jarallax needs to recalculate parallax block size when the browser window resized. So, I don't know how to prevent it on mobile devices and keep working properly. If you have any suggestions or solution - welcome to PR.

**Comment by luchorengo** [comment]
Hi, I'm facing a similar issue when scrolling in mobile, the background scales if on top or bottom screen once you untouch the screen.
The odd thing is that it doesn't happen when I see it in desktop chrome browser using the developer console in mobile mode.
Any idea how to fix it?

**Comment by nk-o** [comment]
@luchorengo hi. You should re-read message by @datune. Mobile browsers add top/bottom bars that cause viewport change (resize the window).

**Comment by gtt25** [comment]
Just a little jerky on mobile devices! But overall it's nice scrolling page! Just missing a matching Navbar with a similar glass parallax scrolling effect, and a Form contact us section! Is it possible to make that? Would be great! As I'm not really good with coding and creating navbar/contact us pages! Or even adding or embedding plugins! So please if anyone have an easy suggestion on how to add those pages and how to link the navigation meneu to the jarallax page, it would be a great favor.
Thanks

**Comment by gtt25** [comment]
Thank you nk-o ! Its working great iPad and Surface.
Is it possible by any chance matching Navbar, a contact us  and Portfolio that match and suit that beautiful glass parallax scrolling effect?
Great job thanks!
