### ISSUE TITLE
1.6 doesn't work without inline background image style

### ISSUE THREAD

**Issue by tandoigai** [nk-o/jarallax#7]
Thank you for great plugin.

I found that the latest version 1.6 doesn't work correctly when we set background image from css, not inline. After digging into your code, I found that you used **el.style** instead of computedStyle so that it only works with inline CSS.

Here's the fix for those need to work with computed css instead of inline css. Open jarallax.js and look for _Jarallax.prototype.css_

```
Jarallax.prototype.css = function (el, styles) {
        var computedStyle = window.getComputedStyle(el);
        if(typeof styles === 'string') {
            return computedStyle.getPropertyValue( styles );
        }

        // add transform prop with vendor prefixes
        if(styles.transform) {
            styles.WebkitTransform = styles.MozTransform = styles.transform;
        }

        for(var k in styles) {
            el.style[k] = styles[k];
        }
        return el;
    };
```

Hope this helps.

**Comment by nk-o** [comment]
Hi, tandoigai.

Thank you for solution! If you have any code fixes or improvements, you can make Pull Requests. This issue will be fixed soon.

Best regards, nK.
