### ISSUE TITLE
using imgRepeat, imgPosition , imgsize data attributes in the latest update 1.9.0

### ISSUE THREAD

**Issue by ashrafreda** [nk-o/jarallax#70]
can i use the imgSize, imgRepeat, imgPosition as a data attribute in the latest update?

**Comment by nk-o** [comment]
Yes, you can. These data-attributes will work: `data-img-size`, `data-img-repeat`, `data-img-position`.

**Comment by ashrafreda** [comment]
Thanks, Nikita.
but why there aren't in the Docs?!

**Comment by nk-o** [comment]
There is data-attribute way example in readme https://github.com/nk-o/jarallax#a-data-attribute-way. Maybe need to add more data attributes in this example.
