### ISSUE TITLE
New update 1.9.0 calculate the clip values on the initial state of the element

### ISSUE THREAD

**Issue by ashrafreda** [nk-o/jarallax#71]
if I use the parallax background for a slider, and the slider takes a min-height before the slides loaded, the parallax clip values still on the initial values. and the result will be a something like this:
![screen shot 2017-11-11 at 4 33 07 pm](https://user-images.githubusercontent.com/16459340/32690351-14bc34d8-c6fe-11e7-8f30-aa26f9808d94.png)

**Comment by nk-o** [comment]
@ashrafreda when your block changed width/height without window resize event, you need to manually call jarallax plugin.

```javascript
$('.jarallax').jarallax('onResize').jarallax('onScroll');
```

**Comment by ashrafreda** [comment]
@nk-o Thanks for your interest,
After the slider is loaded, I call this:
```php
var $parallax = jQuery('.tie-parallax');
if ( $parallax.length ){
   $parallax.jarallax('onResize').jarallax('onScroll');
}
```

but the issue still occurred
it will be fixed if i call the jarallax in the setTimeOut:
```php
setTimeout(function() {
	var $parallax = jQuery('.tie-parallax');
	if ( $parallax.length ){
	    $parallax.jarallax({
		noAndroid: true,
		noIos: true,
	    });
	  }
},100);
```

but I want a real fix instead of using setTimeOut
Thanks Nikita

**Comment by nk-o** [comment]
You call this when you inited slider or when this slider triggered `ready` event? When you inited slider - it is not mean that slider already calculated size. For example, owl carousel ready event: https://owlcarousel2.github.io/OwlCarousel2/docs/api-events.html#initialized-owl-carousel

**Comment by ashrafreda** [comment]
It works.
by using setPosition method in slick
```js
jQuery(slickSlider).on('setPosition', function(slick, direction){
	  console.log(slick);
	  $parallax.jarallax('onResize').jarallax('onScroll');
});
```
Thanks Nikita for writing the amazine parallax
