### ISSUE TITLE
Video Link

### ISSUE THREAD

**Issue by taskall** [nk-o/jarallax#74]
Hi,

Is it possible to add in parallax background a link to pop up youtube video?

**Comment by nk-o** [comment]
Hi.

Jarallax is for background only, no popups. You can add popup by yourself using custom code or different plugin.

**Comment by taskall** [comment]
I am trying to add an <a href using JCE mediaBox but does not work. Is it possible to make it happen?
FYI i am a beginner user

**Comment by nk-o** [comment]
I don't understand why you asking me about it. How to use JCE mediaBox you need to learn in the documentation of this plugin. How to add links, you need to learn how to use HTML and CSS. I can't help you with it.
