### ISSUE TITLE
jarallax on scrollable div

### ISSUE THREAD

**Issue by jmpedrosa** [nk-o/jarallax#76]
Hi, is it posible that the jarallax library is taking scroll events only from the body or window elements and not from any other scrollable divs?

I have a scrollable div deeply nested with a jarallax class and a jarallax-img inside and I can't see the effect working...

**Comment by nk-o** [comment]
Hi.
Could you provide an online example of your page with nested divs and jarallax?

**Comment by nk-o** [comment]
Probably will be added a possibility to work with custom scrollable elements. Further discussions will be here https://github.com/nk-o/jarallax/issues/85
