### ISSUE TITLE
Not working `data attribute way` initialization when making bundle (e.g. webpack) or async load `jarallax` from CDN + Solution

### ISSUE THREAD

**Issue by WhereJuly** [nk-o/jarallax#79]
Thank you a lot for the reaaly small and useful piece of code :100: 

Here is the situation.

**A. Working:**
1) load `jarallax.min.js` via `<script>`
2) use the `data attribute way` initialization
```
<div data-jarallax data-speed="0.2" class="my-bg" style="background-image: url('<background_image_url_here>');">
    Your content here...
</div>
```

**B. Not working:**.

  3) load `jarallax.min.js` from CDN asynchronously by separate JS script OR
  3-A) bundle the script with say Webpack
  4) use the same `data attribute way` as above in 2.

**C. Working:**
 Use 3)  3-A) above and
 5) use the JS initialization way
```
jarallax(document.querySelector('.my-bg'), {
    speed: 0.2
});
```

**Question**
It looks critical not to be able to use Jarallax within Webpack bundle for the case **B** above. Especially when it has to be paired with images lazy-loading utilities. In the post below I propose a couple of solutions.  Could you fix it? Thank you.

On a side note. Can you prefix all the `jarallax`-respective data attributes with `data-jarallax-`? Otherwise it is quite common to have conflicts for `data-img-src` or `data-img-size` etc. with other JS libraries.
I see it could be e.g. `data-jarallax-img-size` etc.

**Comment by WhereJuly** [comment]
Some hints:
I looked at the source code and I see this:

```
```

**Comment by WhereJuly** [comment]
I looked into the source code and I see the solution could be this.

Now you make a main Jarallax start this way.
[link the source](https://github.com/nk-o/jarallax/blob/b81b9ee61dc5c7c3a97d2761dc43dab78c97d8e9/src/jarallax.js#L716)

```
// data-jarallax initialization
addEventListener(window, 'DOMContentLoaded', () => {
    plugin(document.querySelectorAll('[data-jarallax]'));
});
```
It is all the time the case in production when the main JS bundle is loaded at the   `DOMContentLoaded` event. Hence, Jarallax being bundled or loaded asynchronously within a main JS bundle has already missed the event. So the above event listener is never invoked in this case.

The solution is to replace the above with the following code with the following i.e. run the code
```
plugin(document.querySelectorAll('[data-jarallax]'));
```
straight away, with no event at all. To my taste this is better due to shorter code.
The documentation should warn the user about proper handling the call time of Jarallax after DOM or document is ready.

OR, if you still prefer Jarallax to manage call timing itself, the following code would work fine even when `DOMContentLoaded` event has already passed:
```
function start() {
    'use strict';
    var dclhandler;
    if (document.readyState !== 'loading') {
        mainInit();
    } else {
        dclhandler = true;
        document.addEventListener('DOMContentLoaded', mainInit);
    }

    function mainInit() {
        if (dclhandler) {
            document.removeEventListener('DOMContentLoaded', mainInit);
        }
        plugin(document.querySelectorAll('[data-jarallax]'));
    }
}
```
OR

**Comment by MarioPerini** [comment]
No idea why this issue is closed Thank you @WhereJuly for the solution

**Comment by nk-o** [comment]
@MarioPerini if you added it in your code using webpack, you should initialize it by yourself. The script will be run automatically only if you added it in HTML https://github.com/nk-o/jarallax#browser.
