### ISSUE TITLE
Responsive image size

### ISSUE THREAD

**Issue by nonicker** [nk-o/jarallax#8]
Hi, is it possible to scale images so they fit more mobile view (max 480px)?
for example,   the output in responsive (375px screen width)is now:
```
.jarallax {background-attachment: scroll;
  background-size: auto}
```
```
.jarallax-container-5 { width: 375px;
  height: 667px;
  overflow: hidden;
  pointer-events: none;
  transition: transform linear -1ms, -webkit-transform linear -1ms;
  visibility: visible;
  transform: translate3d(0px, -6.2px, 0px);
  background-image: url("picture.jpg");
  background-size: 1186.08px 667px;
  background-position: 50% 50%;
  background-repeat: no-repeat;}
```
Images in responsive mode are too big.  Can their output size be reduced so they fit more in responsive viewport width? Any option to fit image to at least 80% width of background-div in mobile layout?

**Comment by nk-o** [comment]
There is no option for it. Images cover full background size as possible. If we made this scale smaller, you will see that part of parallaxed block have no background.

Anyway, you can change **coverImage** function for your needs.
