### ISSUE TITLE
please remove demo video from dist package

### ISSUE THREAD

**Issue by ivanff** [nk-o/jarallax#80]
75% (283/376), 61.11 MiB | 215 KiB/s
bower progress      jarallax#* Receiving objects:  75% (283/376), 61.33 MiB | 208 KiB/s
bower progress      jarallax#* Receiving objects:  75% (283/376), 61.45 MiB | 207 KiB/s
bower progress      jarallax#* Receiving objects:  91% (343/376), 61.74 MiB | 222 KiB/s
bower progress      jarallax#* Receiving objects:  92% (346/376), 61.74 MiB | 222 KiB/s
bower progress      jarallax#* Receiving objects:  92% (348/376), 62.14 MiB | 270 KiB/s
bower progress      jarallax#* Receiving objects:  93% (350/376), 62.39 MiB | 301 KiB/s

**Comment by nk-o** [comment]
Bower support will be removed in the future updates, we are using npm for now. Will not be fixed.

**Comment by nk-o** [comment]
Bower deprecated since https://github.com/nk-o/jarallax/commit/21878cc6ea1ba38694345de42a33634ebf298700
