### ISSUE TITLE
Different speeds with JQuery

### ISSUE THREAD

**Issue by TiagoDeSousa** [nk-o/jarallax#82]
Is it possible to set different speeds calling the plugin in the JQuery way?

I tried the following but it didn't work. Speeds are always 0.5 in both:

This is my HTML markup:
<section class="parallax" style="background-image:url(image1.jpg);"></section>

<section class="parallax parallax2" style="background-image:url(image1.jpg);"></section>

JQUERY
  $('.parallax').jarallax({
    speed: 0.5,
  });
  $('.parallax2').jarallax({
    speed: 2.0,
  });

**Comment by nk-o** [comment]
It should work. Please, provide an online example, where I can see the bug.
