### ISSUE TITLE
Jarallax not working on iPad

### ISSUE THREAD

**Issue by mig-25** [nk-o/jarallax#84]
hi, 

I can't seem to make jarallax work on my iPad device. It runs fine on my desktop though. 
I made a codepen for this:

https://codepen.io/lupis/pen/62b16e5d6647c438037798403736bf07?editors=1100

What have I missed out on my example?

brgds
Sohail

**Comment by nk-o** [comment]
Hi @mig-25 

I think the problem is not in the code or configuration. It is just because `<iframe>` used on the Codepen. Please, try to check your code on the real site.

**Comment by mig-25** [comment]
Thanks, that worked out :)
