### ISSUE TITLE
Unmute or Change volume after init?

### ISSUE THREAD

**Issue by snade** [nk-o/jarallax#86]
Hello, 
I'm looking for a way to start with the default muted video - "videoVolume: 0",
and then give the users the option to un-mute the video with a button, so increasing the volume after the init.

Is there a way to achieve this using the jarallax plugin? 

Edit:
I saw there are some signs of Mute option in the code, although it's not mentioned in the docs. Maybe we can utilize that somehow?

**Comment by nk-o** [comment]
Hey @snade,

I think it is not possible with the current functionality, but the script could be extended with mute/unmute or volume methods.

Feel free to add this functionality and make a pull request. It could be something like play/pause methods https://github.com/nk-o/jarallax/blob/master/src/jarallax-video.js#L178

**Comment by nk-o** [comment]
It is possible now with the latest plugin version. Example - https://codepen.io/_nK/pen/GQyvdZ

Video API documentation available here - https://github.com/nk-o/video-worker

**Comment by williameduardo79** [comment]
<a id="VideoSound" class="btn btn-white btn-outline" href="#">Mute Video</a>
` $('#VideoSound').click(function () {
            $(this).text(function (i, text) {
                var video = $('#VideoWorker-0');
                if (text == "Mute Video") {
                    
                    video.prop('muted',true);

                    }
                    else {
                    video.prop('muted', false);
                    }
                return text === "Mute Video" ? "Unmute Video" : "Mute Video";
            });
        });`
