### ISSUE TITLE
Jarallax Video options to disable on mobile and use custom fallback image

### ISSUE THREAD

**Issue by daviedR** [nk-o/jarallax#88]
Hi there,

Is there a way to disable the background video on mobile devices and instead of the video could we show a custom fallback image as the parallax on mobile devices?

I know it's great to have background video compatibility for mobile devices, but I think we need an option to disable it. Not many users want to spend bandwidth for background video on their mobile devices.

**Comment by nk-o** [comment]
@daviedR thank you for the idea, will be added such option.

**Comment by daviedR** [comment]
Hmm, how about defining the `disableVideo` and `disableParallax` when user in small browser, not the user agent?

Which means, when user on desktop and resizing the browser window into a small size, the parallax would also be disabled.

**Comment by nk-o** [comment]
@daviedR you can add functions in this option and calculate screen size (Example how to use functions in these options - https://github.com/nk-o/jarallax#disable-on-mobile-devices), it will only called on initial state of jarallax. If you need to dynamically check for screen change, you need to destroy the jarallax and unit it with needed options.

**Comment by nanna-dk** [comment]
Any news on this feature?
And thank you. :)
