### ISSUE TITLE
Jarallax Element wrong anchor point

### ISSUE THREAD

**Issue by daviedR** [nk-o/jarallax#89]
Hi there,

In jarallax element, the parallax effect anchor point is element's top anchor. See pictures below:

![image](https://user-images.githubusercontent.com/1287713/36770825-39b3d6ac-1c7f-11e8-9fbf-726bbc229401.png)

Red line is middle line of the viewport. The element will appear in its original position when its top anchor touch the red line (viewport's middle). This is the problem as when element has more height / width, it doesn't make sense to anymore.

I think anchor point should be the element's center anchor. So when the element's center touch viewport center line, it shows the original position. Or at least, there should be an option for this.

What do you think?

**Comment by nk-o** [comment]
Hi @daviedR .

You absolutely right. I didn't notice this because of the height of the blocks.
Will be fixed soon. Now working on jarallax update.
