### ISSUE TITLE
Jarallax is not recalculated when element size changed

### ISSUE THREAD

**Issue by daviedR** [nk-o/jarallax#90]
Hi,

When we have section that has dynamic content length (such as accordion, load-more grid, etc.),  how to trigger jarallax recalculation?

**Comment by nk-o** [comment]
Hi @daviedR.

In the future updates will be added an experimental feature to automatically check the size of the block and recalculate parallax. For now you can recalculate it manually. Example:

```javascript
$('.jarallax').jarallax('onResize').jarallax('onScroll');
```

**Comment by nk-o** [comment]
Further discussions about automatic recalculation will be here #95
