### ISSUE TITLE
Dynamic content resize

### ISSUE THREAD

**Issue by nk-o** [nk-o/jarallax#95]
When dynamic content changed size of the parallax block, background position not changed.

We can use ResizeObserver with polyfill - https://github.com/que-etc/resize-observer-polyfill

**Comment by daviedR** [comment]
I managed to resize the background position manually using the help of `jquery-elementresize` (https://github.com/rbtbar/jquery-elementresize)

**Comment by daviedR** [comment]
Is there any example how to integrate https://github.com/que-etc/resize-observer-polyfill with Jarallax?

**Comment by nk-o** [comment]
@daviedR you just need to add it to your page and enable ‘automaticResize’ option in jarallax. It should add ResizeObserver polyfill in browsers, where it is not supported.
