### ISSUE TITLE
Unexpected Identifier

### ISSUE THREAD

**Issue by datune** [nk-o/jarallax#99]
```javascript
if(self.type==='youtube'){const availableSizes=['maxresdefault','sddefault','hqdefault','0',];let step=0;const tempImg=new Image();tempImg.onload=function(){if((this.naturalWidth||this.width)!==120||step===availableSizes.length-1){self.videoImage=`https:callback(self.videoImage);}else{step++;this.src=`https:}};tempImg.src=`https:}
```
The above line triggers an Uncaught SyntaxError: Unexpected identifier.

**Comment by nk-o** [comment]
@datune have you enqueued scripts from `src` folder? Please, use the compiled scripts from [`dist`](https://github.com/nk-o/jarallax/tree/master/dist).

**Comment by datune** [comment]
@nk-o Not that I know. I've installed it with npm and in my vendor.js simply call require('jarallax'); It's always worked, until recently. So something must have changed?

**Comment by nk-o** [comment]
@datune I think the problem in the ES6 syntax of the jarallax code. Try to use `babel`. 

How it is used in the repo build:
- https://github.com/nk-o/jarallax/blob/master/.babelrc
- https://github.com/nk-o/jarallax/blob/master/package.json#L40-L43
- https://github.com/nk-o/jarallax/blob/master/gulpfile.babel.js#L60-L71

**Comment by datune** [comment]
@nk-o Hmm, but it has always worked like this, until very recently?

**Comment by nk-o** [comment]
@datune changed in this commit https://github.com/nk-o/jarallax/commit/d15241ae6b8e9c12d8e2282dec29fedc93784a38

**Comment by jnegron357** [comment]
I have the same error except the issue is with the import an export:
![image](https://user-images.githubusercontent.com/3504712/38957363-5ff703be-4328-11e8-9b90-662b99e23fa5.png)

**Comment by nk-o** [comment]
@jnegron357 please use `babel` to transpile code from ES6. Or use script from the `/dist/` directory.
